name: Backend Tests

on:
  push:
    paths:
      - 'be/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    paths:
      - 'be/**'
      - '.github/workflows/backend-tests.yml'

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: |
          cd be
          mvn clean verify -Dspring.profiles.active=test
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/qnotes3_test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: be/target/surefire-reports/
          retention-days: 7

      - name: Report Test Results
        if: always()
        run: |
          echo "Test Summary:"
          find be/target/surefire-reports/ -name "TEST-*.xml" -exec grep -h "<testcase" {} \; | wc -l | xargs echo "Total Tests:"
          find be/target/surefire-reports/ -name "TEST-*.xml" -exec grep -h "<failure" {} \; | wc -l | xargs echo "Failed Tests:"
          find be/target/surefire-reports/ -name "TEST-*.xml" -exec grep -h "<error" {} \; | wc -l | xargs echo "Error Tests:"

      - name: Check Test Results
        if: always()
        run: |
          if [ -n "$(find be/target/surefire-reports/ -name 'TEST-*.xml' -exec grep -l "<failure\|<error" {} \;)" ]; then
            echo "Tests failed"
            exit 1
          fi